### ISSUE TITLE
Extension not showing up in admin panel.

### ISSUE THREAD

**Issue by Aubzilla** [kilianr/phpbb-ext-survey#2]
I had an issue uploading one of the files '.travis.yml'. What I did to resolve it was upload it under another name and rename it once it was uploaded. Is this a valid extension with phpbb? It is not showing up in my admin panel after I have uploaded all the files.

**Comment by kilianr** [comment]
You can skip the file .travis.yml, it is only needed for the automated github tests.
When the extension resides in ext/kilianr/survey, it will show in the admin panel. What version of phpBB are you using?

**Comment by Aubzilla** [comment]
I am using PHP version 5.6 and phpBB 3.2 and locating the file in the directory ext/phpbb-ext-survey-master/. Should I change the file path to ext/kilianr/survey/....? Rename "phpbb-ext-survey-master" as "kilianr" and place all the files in another folder called "survey"? Hence ext/kilianr/survey?

**Comment by Aubzilla** [comment]
Ah! Maybe I have the file path labeled wrong. Mine goes from ext/phpbb-ext-survey-master/ is this correct?

**Comment by Aubzilla** [comment]
HAHA WE HAVE A SUCCESS!!
