### ISSUE TITLE
How do I make the survey questions stack vertically in a normal table?

### ISSUE THREAD

**Issue by Aubzilla** [kilianr/phpbb-ext-survey#3]
My survey questions are stacking horizontally across and off the page. You can scroll to the right and view the questions and answer them all but it's really weird. When I move to mobile view the questions and answers align nicely into a table that flows vertically down the page.

**Comment by kilianr** [comment]
You cannot display the questions vertically in the "normal" (non-mobile) view. This is handled by the stylesheets, I don't (want) to influence that.
However, the questions should not be off the page. I will take a look at this, but it may take a while until I find the time, so be warned... :-)
