### ISSUE TITLE
May I edit questions instead of deleting them entirely?

### ISSUE THREAD

**Issue by Aubzilla** [kilianr/phpbb-ext-survey#6]
I am tired of having to delete all my questions to fix a question. Sometimes there is a flow or structure to a survey that makes it difficult to just delete a question and then try to redo the question by adding it to the end of the survey. So I have to go back and delete questions, it's frustrating and I am wondering if I am using the extension incorrectly or if there isn't a fix for this.

**Comment by kilianr** [comment]
At the questions-tab you can select a quesions (top drop-down menu) in order to edit the question.

If you have questions, do not open issues here but rather ask them at phpbb.com in the extensions' thread please.
